### PR TITLE
25 from until fixes

### LINKED ISSUE #1: Epic: Refactoring of the XOAI library
- [x] Remove Log4J usage and any dependencies using it
- [x] Use ~~System.Logger~~ SLF4J for logging
- [ ] Add docs on how to set log levels from using applications
- [x] Switch all tests to JUnit5
- [x] Switch all `java.util` time classes to `java.time` classes
- [x] Try to get rid of `com.lyncode.xml`
- [x] Use modern Java XML Binding and writing
- [x] Update Hamcrest (replace?)
- [x] Switch all packages from `org.dspace` to `io.gdcc`
- [x] Remove Apache HTTP client and use JVM native (makes the lib JDK11+)
- [x] Use Java 8/11 constructs like autoclosables, streams etc
- [ ] Provide interfaces used as XOAI extension points for application with default methods (e. g. for data-provider sets interfaces)
- [ ] Double-check every module for reading back data from a stream that might not contain data due to a writer buffer (this caused trouble that appeared as failing tests)

### LINKED ISSUE #2: Port changes from IQSS XOAI fork to v4
At https://github.com/IQSS/dataverse/tree/develop/local_lib/com/lyncode lives a local fork of an old version of this library.

We need to compare these sources to an old Lyncode release and look if and how to incorporate these changes. (Maybe things got fixed or refactored making the change obsolete...)

Apparently this is tricky: we have source JARs for data provider and service provider, but we did not add our common source JAR. Decompilation reveals the code, but comparison gets much harder this way! (And the context aka why sth was changed is lost...)

### LINKED ISSUE #10: Coordinate with Dataverse upstream to incorporate optimizations
The Dataverse main software uses this library to create an OAI-PMH server. To achieve maximum performance, they kind of forked some of the classes this library provides, copying most of the code.

As this is now a fork under the control of GDCC, it would make sense to change the library classes to provide useful extension points that Dataverse codebase could use then to avoid maintaining forked classes.

@landreev WDYT?

The respective Dataverse classes can be found here: 
- [edu.harvard.iq.dataverse.harvest.server.xoai](https://github.com/IQSS/dataverse/tree/develop/src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai)

### LINKED ISSUE #25: Bug: protocol spec violation with date ranges
Currently,  [`OAICompileRequest.validateDates()`](https://github.com/gdcc/xoai/blob/a31dc7cee56001ee02d60466fe0e1359e0799f8e/xoai-data-provider/src/main/java/io/gdcc/xoai/dataprovider/parameters/OAICompiledRequest.java#L265-L273) checks if `from` is after `until`. This is a clear protocol violation!

> 2.7.1 Selective Harvesting and Datestamps
> 
> Harvesters may use datestamps to harvest only those records that were created, deleted, or modified within a specified date range. To specify datestamp-based selective harvesting, datestamps are included as values of the optional arguments, from and until, in the [ListRecords](http://www.openarchives.org/OAI/openarchivesprotocol.html#ListRecords) and [ListIdentifiers](http://www.openarchives.org/OAI/openarchivesprotocol.html#ListIdentifiers) requests. Harvesting is restricted to the range specified by the from and until arguments, extending back to the earliest datestamp if from is omitted, and forward to the most recent datestamp if until is omitted. **Range limits are inclusive**: from specifies a bound that must be interpreted as "greater than or equal to", until specifies a bound that must be interpreted as "less than or equal to". Therefore, the from argument must be **less than or equal to** the until argument. Otherwise, a repository must issue a badArgument error.
> 
> Repositories must support selective harvesting with the from and until arguments expressed at day granularity. Optional support for seconds granularity is indicated in the response to the [Identify](http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify) request. The value of datestamps in both requests and responses must comply to the specifications for [UTCdatetime](http://www.openarchives.org/OAI/openarchivesprotocol.html#Dates) in this document. A repository must update the datestamp of a record if a change occurs, the result of which would be a change to the [metadata part](http://www.openarchives.org/OAI/openarchivesprotocol.html#metadatapart) of the XML-encoding of the record. Such changes include, but are not limited to, changes to the metadata of the record, changes to the metadata format of the record, introduction of a new metadata format, termination of support for a metadata format, etc.

This is especially a problem with day granularity.

~~It also does not check for conformance with using the same granularity for both dates~~: (it does by comparing the string length...)

> 3.3.1 UTCdatetime in Protocol Requests
> 
> [Datestamps](http://www.openarchives.org/OAI/openarchivesprotocol.html#Datestamp) used as values of the optional arguments from and until in the [ListIdentifiers](http://www.openarchives.org/OAI/openarchivesprotocol.html#ListIdentifiers) and [ListRecords](http://www.openarchives.org/OAI/openarchivesprotocol.html#ListRecords) requests are encoded using [ISO8601](http://www.w3.org/TR/NOTE-datetime) and are expressed in UTC. These arguments are used to specify [datestamp-based selective harvesting](http://www.openarchives.org/OAI/openarchivesprotocol.html#Datestamp). These arguments support the "Complete date" and the "Complete date plus hours, minutes and seconds" granularities defined in ISO8601. The legitimate formats are YYYY-MM-DD and YYYY-MM-DDThh:mm:ssZ. **Both arguments must have the same granularity.** All repositories must support YYYY-MM-DD. A repository that supports YYYY-MM-DDThh:mm:ssZ should indicate so in the [Identify](http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify) response. A request by a harvester with finer granularity than that supported by a repository must produce an [error](http://www.openarchives.org/OAI/openarchivesprotocol.html#ErrorConditions).

The timestamps are also only validated if both `from` and `until` are present, which is incorrect (see first quote above). It's debatable if the `until` should default to `now()`, as no future dates are possible. At least both `from` and `until` should be checked to not be within the future.

Also, the request MUST use the granularity given within the `Configuration` and complain about others. Plus, the configuration contains an "earliest date", which `from` may not surpass

- [x] Check `from` against earliest date from Config
- [x] Check `from` and `until` is not in the future
- [x] Check `from` is before or equal to `until`
- [x] Check `from` and `until` use the granularity given in Configuration
- [X] Optional: check `from` and `until` use the same granularity ([already done](https://github.com/gdcc/xoai/blob/a31dc7cee56001ee02d60466fe0e1359e0799f8e/xoai-data-provider/src/main/java/io/gdcc/xoai/dataprovider/parameters/OAICompiledRequest.java#L94-L99))
- [x] Make sure `until` is `atEndOfDay() ` when using "day" granularity
- [ ] Default `until` to now/this day
- [ ] Ensure the resumption token sourced `from` and `until` does not circumvent this (it does now, because loading happens after validation)
- [ ] Investigate into remove the `DateProvider.parse(Sring)` method to enforce using the configured granularity everywhere

### PR DESCRIPTION
**Pull request by poikilotherm**
Closes #25 
Closes #1 
Closes #10 
Closes #2

Besides the pure fix, this is also a larger refactoring of the classes, as the fix wasn't so easy to implement within the current flow of the data provider.

### CODE REVIEW

**Comment by poikilotherm** [comment]
(Of course this is not ready - the handlers need to be fixed and aligned to the new structure yet. And we need tests. TESTS :smile: )

**Comment by poikilotherm** [comment]
@landreev I think this is done.

One TODO might remain: verification of a resumption token value encoded data. What do you think - should this be addressed in this PR or left as an exercise for later?

**Comment by poikilotherm** [comment]
It's Friday. Perfect time for shipping!

**Comment by landreev** [comment]
> verification of a resumption token value encoded data.

A perfect candidate for an "exercise for later", yes.

**Pull request merged**
