### PR TITLE
Custom http headers in OaiClient (#118)

### LINKED ISSUE #118: Add a mechanism for configuring OaiClients to send custom http headers with OAI requests
This is to accommodate IQSS/dataverse/issues/9231. This can be achieved by simply making the class io.gdcc.xoai.serviceprovider.client.JdkHttpOaiClient non-final, then extending it with the extra functionality on the Dataverse side. But based on a quick discussion in the issue above, it would make more sense to add it to the xoai code here. Will make a PR shortly.

### PR DESCRIPTION
**Pull request by landreev**
These are the code changes I checked in yesterday. I re-tested building Dataverse with my local jar files built from this xoai branch, things appear to be working. 
Please let me know if anything needs to be changed/reorganized. 

Closes #118

### CODE REVIEW

**Comment by landreev** [comment]
I'm not sure I understand what the "format violations" are behind the failed checks (?) - but I'll try to figure it out.

**Comment by poikilotherm** [comment]
> I'm not sure I understand what the "format violations" are behind the failed checks (?) - but I'll try to figure it out.

The `pre-commit` hooks will probably help. https://github.com/gdcc/xoai#development :wink:

**Comment by poikilotherm** [comment]
I will go ahead with merging @landreev if you are satisfied with the changes I made.

Also, the test coverage is not >70% for the new lines, but I am going to ignore that this time, as it would be hard to do a test for the actual client without using something like WireMock to avoid failing HTTP requests.

**Comment by landreev** [comment]
The changes look great; a Map is of course prettier to deal with. 
Thank you!

**Pull request merged**
