### PR TITLE
Fix for default namespace overwritten by empty namespace

### LINKED ISSUE #240: Empty namespaces on attributes overwriting the default namespace
We would like to use your library as an implementation for our OAI PMH dataprovider API.
However we are running into a problem with the transformation during the `GetRecord` operation.

We have developed an XSLT script that transforms a TEI XML document into a Dublin Core XML document. When we apply this script to our XML document in an XML editor such as IntelliJ or Oxygen, the result is as expected. However, when using this library, we encounter issues related to namespaces.

In accordance with the TEI XML standard, the TEI Namespace is designated as the default namespace.
Upon debugging the code for "GetRecord" and setting a breakpoint in the class "MetadataHelper.java:20," it became evident that the value of "metadata" was accurate. After executing line 20, a number of empty namespaces (specified as "xmlns="") were appended to a series of tags, including "name" and "ptr," as illustrated in the following example:
(The following example has been shortened for the sake of brevity.)

```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader xml:lang="de">
      ...
      <publicationStmt>
        <publisher>
          <name xmlns="" type="org">Org</name>
          <ptr xmlns="" target="http://www.org.de"/>
        </publisher>
        ...
      </publicationStmt>
      ...
  </teiHeader>
</TEI>
```

This results in the failure of the transformation, and our Dublin Core XML is composed solely of empty tags. Upon debugging in `metadata.write(writer)`, it ultimately reaches `EchoElement.java:66`. At this point, it can be observed that when the tag `<name>` is processed, the correct namespace (`http://www.tei-c.org/ns/1.0`) is mapped to it.

Once we get to the part where we're processing a tag with an attribute, we can take a peek at EchoElement.java:84. There, we'll see that the attribute is linked to an empty namespace. This means that the XML will have "xmlns=" written to it.

Upon commenting out `EchoElement.java:85`, the entire transformation functions as intended, yielding a valid Dublin Core XML. Given my limited expertise in XML, XML Namespaces, and XSLT, I am uncertain about the optimal solution that would not disrupt other use cases.

Should you require further information, kindly let me know and I will provide it.

### PR DESCRIPTION
**Pull request by bumann-sbb**
Fixes #240 

Fix for default namespace overwritten by empty namespace
Fixed a few SonarLint warnings

### CODE REVIEW

**Comment by bumann-sbb** [comment]
@pdurbin Now the pipeline throws following, which seems like something I can't fix or am I missing something?

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar 
(default-cli) on project xoai: Project not found. 
Please check the 'sonar.projectKey' and 'sonar.organization' properties, 
the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions 
of the user the token belongs to -> [Help 1]
```

**Comment by pdurbin** [comment]
@bumann-sbb yikes. Probably not.

I wonder... is it because the workflow only works properly under the main repo (gdcc) and not in a fork (such as bumann-sbb).

@poikilotherm any thoughts on this? And the PR overall. 😄

**Review by poikilotherm — APPROVED** [review]
Added a fix for pre-commit and some restyling in the test.

Well done! Thanks for also adding a test case! Perfect PR. Will merge and cut a release soon!

(Don't worry about SonarCloud. As this is a PR from a fork, you don't get access to the secrets necessary to commit the results.)

**Comment by bumann-sbb** [comment]
@pdurbin @poikilotherm 
Thank you both very much. It was a pleasure to contribute! :)

**Comment by poikilotherm** [comment]
Thanks for your contribution! Even with a unit test! That's how Open Source is meant to be. ❤️

**Pull request merged**
